### PR TITLE
Added support for brotli compression

### PR DESCRIPTION
**Pull request by nrotta**
Added support for brotli compression. The required changes to inert and hapi have also been done and the PRs submitted for merging.

This PR implements the following: https://github.com/hapijs/hapi/issues/3037

### CODE REVIEW

**Comment by nrotta** [comment]
Not sure why the CI is failing.

**Comment by gergoerdosi** [comment]
As I can see you added `iltorb` to dependencies which has a dependency on `nan`. So this part of the Travis output might be relevant:

> Starting with io.js 3 and Node.js 4, building native extensions requires C++11-compatible compiler, which seems unavailable on this VM. Please read https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.

**Comment by hueniverse** [comment]
Please hold off on adding this. I really don't want these new deps in core. We'll need to figure out how to allow this as a plugin.

**Comment by nrotta** [comment]
@gergoerdosi thanks. I will take a look.

@hueniverse happy to try adding it as a plugin if you point me in the right direction on how that should be done.

**Comment by nrotta** [comment]
@gergoerdosi it seems that this will be added as a plugin but in any case I fixed the failing test on Travis.

**Comment by johnbrett** [comment]
Just FYI, I'm on holidays till the 24th, will review everything on return.

**Comment by nrotta** [comment]
@johnbrett @hueniverse I don't know. If it is decided to go with a plugin, I'm happy to take on the work if someone pointed me in the right direction.

**Comment by hueniverse** [comment]
It's still in my queue.

**Comment by hueniverse** [comment]
This will got into a new hapi plugins with v15.

**Pull request closed without merging**
