### PR TITLE
Return 413 when payload too large.

### PR DESCRIPTION
**Pull request by aheinz-fe**
From https://github.com/hapijs/discuss/issues/516

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
If this passes does this not mean we are missing a test case?

**Comment by devinivy** [comment]
I definitely expected a breakage.  My guess is that the test is just permissive.  I'll try to dig it up.

**Comment by AdriVanHoudt** [comment]
But err.statusCode in that test has changed no?

**Comment by devinivy** [comment]
That test doesn't check `err.output.statusCode`!  It certainly could, though.

**Comment by AdriVanHoudt** [comment]
Imo it should ^^

**Comment by aheinz-fe** [comment]
Commit amended.

**Comment by johnbrett** [comment]
Great work @aheinz-fe! Merged, and well spotted on that test case, it should have checked the statusCode.

**Pull request merged**
